import { Chart,LineController,LineElement,PointElement,LinearScale,Tooltip,Filler,type ChartDataset } from 'chart.js';
import { MONTHS,YEAR } from './year';
import './styles.css';
import { bee, flower, icon } from './nature';
Chart.register(LineController,LineElement,PointElement,LinearScale,Tooltip,Filler);
type Point={t:number;v:number};
type Hive={key:string;name:string;color:string;latest:Point|null;delta24:number|null;delta7:number|null;reference24:number|null;reference7:number|null;firstAt:number|null;jump:{t:number;delta:number}|null;points:Point[]};
type Data={source:string;generatedAt:number;start:number;end:number;days:number;bucketSeconds:number;hives:Hive[];sync:{channel:number;cursor_at:string|null;succeeded_at:string|null;attempted_at:string|null;last_error:string|null}[]};
const number=new Intl.NumberFormat('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(t:number,full=false)=>new Intl.DateTimeFormat('de-DE',{timeZone:'Europe/Berlin',day:'2-digit',month:'2-digit',...(full?{year:'numeric' as const}:{}),hour:'2-digit',minute:'2-digit'}).format(t);
const delta=(v:number|null)=>v===null?'—':`${v>0?'+':v<0?'−':''}${number.format(Math.abs(v))}`;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const actualMonth=Number(new Intl.DateTimeFormat('en',{month:'numeric',timeZone:'Europe/Berlin'}).format(new Date()))-1;
let month=actualMonth,days=7,relative=false,data:Data|null=null,chart:Chart<'line'>|null=null,busy=false,requestId=0;
const hidden=new Set<string>();
const refreshIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M20 7v5h-5M4 17v-5h5"/><path d="M6.1 7a7 7 0 0 1 11.8-1L20 9M4 15l2.1 3A7 7 0 0 0 18 17"/></svg>';
document.querySelector<HTMLDivElement>('#app')!.innerHTML=`
<header class="topbar"><div class="top-inner"><a href="/" class="brand"><img src="/favicon.svg" alt="" width="36" height="36"><span>Bienenstand<span class="brand-small">Deine vier Völker im Blick</span></span></a><nav aria-label="Hauptnavigation"><a href="#overview" class="nav-active">Übersicht</a><a href="#bienenjahr">Bienenjahr</a><a href="#archive">Archiv</a></nav></div></header>
<main><section id="overview" aria-labelledby="main-title"><div class="hero"><div class="hero-copy"><h1 id="main-title">Wie geht’s<br>den Bienen?</h1><span class="hero-bee">${bee}</span></div><div class="hero-art"><img src="/images/meadow.webp" alt="Vier farbige Bienenbeuten in einer blühenden Wiese" fetchpriority="high" width="1200" height="800"></div></div>
<div class="overview-tools"><button id="refresh" class="refresh">${refreshIcon}<span>Aktualisieren</span></button></div>
<div class="status-line"><span id="status" role="status" aria-live="polite">Archiv wird geladen …</span><span class="timezone">Alle Zeiten: Europe/Berlin</span></div>
<div id="message" role="status" aria-live="polite"></div><div id="cards" class="cards" aria-busy="true">${Array.from({length:4},()=>'<div class="hive-card skeleton"><div></div><div></div><div></div></div>').join('')}</div>
<div class="workspace"><section class="chart-panel" aria-labelledby="chart-title"><div class="panel-heading"><div><h2 id="chart-title"><span class="heading-icon">${icon('chart')}</span>Gewichtsverlauf</h2><p class="panel-subtitle">Entwicklung der vier Völker im Vergleich</p></div><div class="ranges" role="group" aria-label="Zeitraum">${[[1,'24 h'],[7,'7 Tage'],[30,'30 Tage'],[365,'1 Jahr']].map(([v,label])=>`<button data-days="${v}" aria-pressed="${v===7}">${label}</button>`).join('')}</div></div>
<div class="chart-options"><div id="legend" class="legend" role="group" aria-label="Völker im Diagramm"></div><label class="compare"><input id="relative" type="checkbox"><span>Änderung seit Beginn</span></label></div><div class="chart-wrap"><canvas id="chart" role="img" aria-label="Gewichtsverlauf der ausgewählten Bienenvölker"></canvas><p id="chart-empty" hidden></p></div><div class="chart-footer"><span id="chart-note">Messwerte werden geladen.</span><span>Tippen für Messwerte</span></div><details class="data-detail"><summary>Messwerte als Tabelle</summary><div id="data-table"></div></details></section>
<aside class="insights" aria-labelledby="insight-title"><h2 id="insight-title"><span class="leaf-icon">${icon('leaf')}</span>Am Stand im Blick</h2><div id="insights"><p class="muted">Hinweise werden geladen.</p></div><p class="aside-note">Gewichtssprünge können von Fütterung, Ernte, Wetter oder einem Schwarm kommen. Die Waage gibt Hinweise, keine Diagnose.</p></aside></div></section>
<section id="bienenjahr" class="year-panel" aria-labelledby="year-title"><div class="year-heading"><div><h2 id="year-title"><span class="heading-icon">${icon('calendar')}</span>Bienenjahr</h2><p class="panel-subtitle">Saisonale Aufgaben und Hinweise für deinen Stand</p></div><span class="dadant">Dadant · Augsburg</span></div><div class="month-strip" role="group" aria-label="Monat wählen">${MONTHS.map((m,i)=>`<button data-month="${i}" aria-pressed="${i===month}" ${i===actualMonth?'class="current-month"':''}>${m.slice(0,3)}${i===actualMonth?'<span class="sr-only"> – aktueller Monat</span>':''}</button>`).join('')}</div><div id="month-content"></div><p class="year-note">Orientierung für deinen Bienenstand: Wetter, Volksentwicklung, Tracht und Varroabefall gehen immer vor dem Kalendermonat.</p><details class="sources"><summary>Fachliche Grundlagen</summary><p>Monatliche Orientierung für Dadant, keine Dosierungsanleitung. Behandlung nur mit zugelassenem Präparat und nach dessen Gebrauchsinformation sowie Geräteanleitung.</p><a href="https://www.lwg.bayern.de/bienen/haltung/096308/index.php" target="_blank" rel="noopener">LWG: Bienenpflege</a><a href="https://www.lwg.bayern.de/bienen/krankheiten/094761/index.php" target="_blank" rel="noopener">LWG: Sommerbehandlung</a><a href="https://www.lwg.bayern.de/bienen/krankheiten/093088/index.php" target="_blank" rel="noopener">LWG: Winterbehandlung</a></details></section>
<footer><span>${icon('leaf')} Bienenstand</span><details id="archive"><summary>Archiv & Datenstand</summary><div id="archive-detail">Noch keine Daten geladen.</div></details></footer></main>`;
const el=(id:string)=>document.getElementById(id)!;
function age(t:number){const m=Math.max(0,Math.floor((Date.now()-t)/60000));return m<1?'gerade eben':m<60?`vor ${m} Min.`:m<1440?`vor ${Math.floor(m/60)} Std.`:`vor ${Math.floor(m/1440)} Tagen`;}
function stale(h:Hive){return !h.latest||Date.now()-h.latest.t>3600000;}
function setMessage(text:string,error=false){el('message').innerHTML=text?`<div class="message ${error?'error':''}">${escape(text)}</div>`:'';}
function renderCards(){if(!data)return;
 el('cards').setAttribute('aria-busy','false');
 el('cards').innerHTML=data.hives.map((h,i)=>`<article class="hive-card" style="--hive:${h.color}"><div class="card-top"><h2><span class="hive-mark" aria-hidden="true"></span>${h.name}</h2><span class="card-state ${stale(h)?'late':''}">${stale(h)?'Veraltet':'Aktuell'}</span></div><div class="hive-body"><img class="hive-art" src="/images/hive-${i}.webp" alt="" width="240" height="240"><div class="hive-numbers"><div class="weight">${h.latest?number.format(h.latest.v):'—'}<span>kg</span></div><div class="deltas"><div><span>24 Stunden</span><strong class="${h.delta24!==null&&h.delta24<0?'negative':'positive'}">${delta(h.delta24)} <small>${h.delta24!==null?'kg':''}</small></strong></div><div><span>7 Tage</span><strong class="${h.delta7!==null&&h.delta7<0?'negative':'positive'}">${delta(h.delta7)} <small>${h.delta7!==null?'kg':''}</small></strong></div></div></div></div><div class="card-bottom"><span class="mini-trend" aria-hidden="true">${h.delta24===null?'—':h.delta24>0?'↗':h.delta24<0?'↘':'→'}</span><span>${h.latest?`<time datetime="${new Date(h.latest.t).toISOString()}" title="${date(h.latest.t,true)}">${date(h.latest.t)} · ${age(h.latest.t)}</time>`:'Keine Messung vorhanden'}</span></div></article>`).join('');
 const old=data.hives.filter(stale);el('status').innerHTML=`<span class="status-dot ${old.length?'warning':''}"></span>${old.length?`${old.length} von 4 Völkern ohne frische Messung`:'Alle 4 Völker senden Daten'} <span class="status-extra">· Abgerufen ${new Intl.DateTimeFormat('de-DE',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Berlin'}).format(data.generatedAt)}</span>`;
 el('legend').innerHTML=data.hives.map(h=>`<button data-hive="${h.key}" aria-pressed="${!hidden.has(h.key)}" style="--hive:${h.color}"><span class="legend-dot"></span>${h.name.replace(' Volk','').replace('-Volk','')}</button>`).join('');
 renderInsights();
 el('archive-detail').innerHTML=`<p>Rohmesswerte werden dauerhaft archiviert. Änderungen beziehen sich auf die letzte Messung und einen Vergleichswert höchstens 60 Minuten vor dem Zielzeitpunkt. Fehlt dieser, steht dort „—“.</p><ul>${data.hives.map(h=>`<li>${h.name}: seit ${h.firstAt?date(h.firstAt,true):'—'}</li>`).join('')}</ul><h3>Letzter erfolgreicher Abruf je Kanal</h3><ul>${data.sync.map(s=>`<li>${s.channel}: ${s.succeeded_at?date(Date.parse(s.succeeded_at),true):'noch kein Abruf'}${s.last_error?' · Abruf fehlgeschlagen':''}${s.cursor_at?`<br>Rückstände geprüft bis ${date(Date.parse(s.cursor_at),true)}`:''}</li>`).join('')}</ul><p>Automatischer Abgleich etwa alle 15 Minuten. GitHub Actions kann Ausführungen verzögern. Rohwerte bleiben auch bei verdichteter Diagrammansicht erhalten.</p>`;
}
function renderInsights(){if(!data)return;const items:{title:string;text:string;warn:boolean}[]=[];
 for(const h of data.hives){if(stale(h))items.push({title:`${h.name}: Daten fehlen`,text:h.latest?`Letzte Messung ${date(h.latest.t)}. Waage, Verbindung und Import prüfen.`:'Noch keine Messwerte vorhanden.',warn:true});if(h.jump)items.push({title:`${h.name}: Gewichtssprung`,text:`${delta(h.jump.delta)} kg zwischen zwei Messungen · ${date(h.jump.t)}. Eingriff oder Ursache prüfen.`,warn:true});}
 if(data.sync.some(s=>s.last_error))items.push({title:'Archivierung prüfen',text:'Mindestens ein Kanal konnte zuletzt nicht vollständig abgerufen werden. Vorhandene Messwerte bleiben sichtbar.',warn:true});
 if(!items.length){items.push({title:'Keine großen Sprünge',text:'In den letzten 24 Stunden kein Sprung ab 2 kg zwischen Messungen mit höchstens 30 Minuten Abstand erkannt.',warn:false});const hs=data.hives.filter(h=>h.delta24!==null);if(hs.length){const down=hs.filter(h=>h.delta24!<0).length;items.push({title:down===hs.length?'Alle Völker nehmen ab':down===0?'Alle Völker stabil oder im Plus':`${down} von ${hs.length} Völkern nehmen ab`,text:'Vergleich zum Gewicht vor 24 Stunden. Futtergaben und Arbeiten an den Beuten mit berücksichtigen.',warn:false});}}
 el('insights').innerHTML=items.map(i=>`<div class="insight"><span class="insight-icon ${i.warn?'warn':''}" aria-hidden="true">${icon(i.warn?'alert':'leaf')}</span><div><h3>${i.title}</h3><p>${i.text}</p></div></div>`).join('');
}
function drawChart(){if(!data)return;chart?.destroy();
 const visible=data.hives.filter(h=>!hidden.has(h.key)),hasPoints=visible.some(h=>h.points.length);
 el('chart-empty').hidden=hasPoints;el('chart-empty').textContent=visible.length?'Keine Messwerte in diesem Zeitraum.':'Wähle mindestens ein Volk aus.';
 const formatTick=(t:number)=>new Intl.DateTimeFormat('de-DE',{timeZone:'Europe/Berlin',...(days===1?{hour:'2-digit' as const,minute:'2-digit' as const}:days===365?{month:'short' as const}:{day:'2-digit' as const,month:'2-digit' as const})}).format(t);
 const datasets:ChartDataset<'line'>[]=data.hives.map(h=>{
  const base=relative?(h.points[0]?.v??0):0;
  // Explicit breaks prevent drawing across outages, even after server-side reduction.
  const points:{x:number;y:number|null}[]=[];
  h.points.forEach((p,i)=>{if(i&&p.t-h.points[i-1].t>Math.max(data!.bucketSeconds*2000,3600000))points.push({x:p.t-1,y:null});points.push({x:p.t,y:p.v-base});});
  return {label:h.name,data:points as any,borderColor:h.color,backgroundColor:h.color,borderWidth:2,pointRadius:h.points.length===1?3:0,pointHoverRadius:5,pointHitRadius:14,tension:0,spanGaps:false,hidden:hidden.has(h.key)};
 });
 chart=new Chart<'line'>(el('chart') as HTMLCanvasElement,{type:'line',data:{datasets},options:{responsive:true,maintainAspectRatio:false,animation:false,normalized:true,parsing:false,interaction:{mode:'nearest',intersect:false},plugins:{legend:{display:false},tooltip:{backgroundColor:'#493422',padding:12,displayColors:true,callbacks:{title:items=>items.length?date(items[0].parsed.x!,true):'',label:ctx=>`${ctx.dataset.label}: ${relative?delta(ctx.parsed.y):number.format(ctx.parsed.y!)} kg`}}},scales:{x:{type:'linear',min:data.start,max:data.end,grid:{display:false},border:{display:false},ticks:{maxTicksLimit:window.innerWidth<600?4:7,color:'#887b69',font:{size:12},callback:value=>formatTick(Number(value)),maxRotation:0}},y:{title:{display:true,text:relative?'Änderung · kg':'Gewicht · kg',color:'#887b69'},border:{display:false},grid:{color:'#eee7d9'},ticks:{maxTicksLimit:6,color:'#887b69',font:{size:12},callback:value=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:1}).format(Number(value))}}}}});
 el('chart-note').textContent=`${days===1?'5-Minuten':days===7?'30-Minuten':days===30?'2-Stunden':'Tages'}-Fenster · Anfang, Tief, Hoch & Ende${relative?' · Je Volk ab erstem Wert im Zeitraum':''}`;
 const rows=visible.flatMap(h=>h.points.map(p=>({h,p}))).sort((a,b)=>b.p.t-a.p.t).slice(0,80);
 el('data-table').innerHTML=`<p>Die letzten ${rows.length} dargestellten Messpunkte der ausgewählten Völker. Die Tabelle zeigt die ursprünglichen Gewichte.</p><table><thead><tr><th>Zeit</th><th>Volk</th><th>kg</th></tr></thead><tbody>${rows.map(({h,p})=>`<tr><td>${date(p.t)}</td><td>${h.name}</td><td>${number.format(p.v)}</td></tr>`).join('')}</tbody></table>`;
}
function renderMonth(){const m=YEAR[month];el('month-content').innerHTML=`<div class="month-intro"><span class="season-art" aria-hidden="true">${flower}${bee}</span><div><span class="month-label">${MONTHS[month]} <span>/${m.season}</span></span><h3>${m.title}</h3></div><p>${m.watch}</p></div><div class="year-tasks">${m.items.map(([title,text],i)=>`<article><span class="task-number" aria-hidden="true">${icon('check')}</span><div><h4>${title}</h4><p>${text}</p></div></article>`).join('')}</div>`;document.querySelectorAll<HTMLButtonElement>('[data-month]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.month)===month)));}
async function load(){const id=++requestId;try{const r=await fetch(`/api/history?days=${days}`,{cache:'no-store',signal:AbortSignal.timeout(60000)});if(!r.ok)throw new Error('Archiv konnte nicht geladen werden. Bitte erneut versuchen.');const next=await r.json() as Data;if(!Array.isArray(next.hives)||next.hives.length!==4)throw new Error('Unerwartete Antwort des Archivs.');if(id!==requestId)return;data={...next,hives:next.hives.map((h,i)=>({...h,color:['#c95642','#e7aa27','#668c4a','#4c92ba'][i]}))};renderCards();drawChart();}catch(error){if(id!==requestId)return;setMessage(error instanceof Error?error.message:'Verbindung fehlgeschlagen.',true);if(!data){el('cards').innerHTML='<p class="empty-card">Noch keine Messwerte geladen. Mit „Aktualisieren“ erneut versuchen.</p>';el('status').textContent='Archiv nicht erreichbar';}throw error;}}
async function refresh(){if(busy)return;busy=true;const button=el('refresh') as HTMLButtonElement;button.disabled=true;button.classList.add('spinning');button.querySelector('span')!.textContent='Wird aktualisiert';setMessage('Neue Messwerte werden abgerufen …');
 try{const r=await fetch('/api/sync',{method:'POST',signal:AbortSignal.timeout(190000)});const result=await r.json();if(!r.ok||!result.ok)throw new Error('Abruf nicht vollständig. Vorhandene Archivdaten werden angezeigt.');await load();setMessage(result.skipped?'Archiv neu geladen. Der letzte Import läuft noch oder liegt weniger als zwei Minuten zurück.':'Messwerte und Archiv aktualisiert.');}
 catch(error){try{await load();}catch{}setMessage(error instanceof Error?error.message:'Aktualisierung fehlgeschlagen.',true);}finally{busy=false;button.disabled=false;button.classList.remove('spinning');button.querySelector('span')!.textContent='Aktualisieren';}}
el('refresh').addEventListener('click',refresh);
document.querySelectorAll<HTMLButtonElement>('[data-days]').forEach(b=>b.addEventListener('click',async()=>{days=Number(b.dataset.days);document.querySelectorAll<HTMLButtonElement>('[data-days]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));el('chart-note').textContent='Zeitraum wird geladen …';try{await load();setMessage('');}catch{}}));
el('legend').addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-hive]');if(!b)return;const key=b.dataset.hive!;hidden.has(key)?hidden.delete(key):hidden.add(key);b.setAttribute('aria-pressed',String(!hidden.has(key)));drawChart();});
el('relative').addEventListener('change',e=>{relative=(e.target as HTMLInputElement).checked;drawChart();});
document.querySelectorAll<HTMLButtonElement>('[data-month]').forEach(b=>b.addEventListener('click',()=>{month=Number(b.dataset.month);renderMonth();}));
renderMonth();void load().catch(()=>{});
setInterval(()=>{if(!document.hidden&&!busy)void load().catch(()=>{});},300000);
