export const MONTHS=['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'];
export const YEAR: {title:string;season:string;items:[string,string][];watch:string}[]=[
 {title:'Ruhe bewahren. Vorräte im Blick.',season:'Winterruhe',items:[['Futterkontrolle','Gewichtsverlauf beobachten und Vorräte vorsichtig prüfen. Beutengewicht ist ohne Leergewicht keine Futtermenge.'],['Flugloch & Stand','Flugloch freihalten, Mäuseschutz und sicheren Stand kontrollieren. Unnötiges Öffnen vermeiden.']],watch:'Ein stetiger Rückgang ist im Winter normal. Auffällige Verluste mit Wetter und Arbeiten am Volk abgleichen.'},
 {title:'Gut durch den Spätwinter.',season:'Winterruhe',items:[['Futter erreichbar?','Mit beginnender Brut steigt der Verbrauch. Auf erreichbare Reserven achten; bei Mangel rechtzeitig helfen.'],['Saison vorbereiten','Rähmchen, Mittelwände, Schiede und Honigräume vorbereiten. Reinigungsflüge beobachten.']],watch:'Brutbeginn richtet sich nach Witterung und Volk – nicht nach dem Kalender.'},
 {title:'Mit dem Volk in den Frühling.',season:'Auswinterung',items:[['Auswinterung','Bei geeignetem Flugwetter Futter, Volksstärke und Weiselrichtigkeit prüfen.'],['Dadant-Brutraum','Schied an besetzte Waben und Entwicklung anpassen. Futterzugang sichern; Brutnest nicht auseinanderreißen.'],['Boden & Futter','Boden bei Bedarf reinigen und knappe Vorräte ergänzen.']],watch:'Kältephasen und steigender Brutumfang können die Vorräte schnell verringern.'},
 {title:'Raum für den Aufschwung.',season:'Frühjahrsentwicklung',items:[['Honigraum geben','Bei ausreichender Volksstärke und einsetzender Tracht rechtzeitig Platz schaffen.'],['Schied nachführen','Brutraum bedarfsgerecht erweitern. Besatz und Brutbild sind entscheidend.'],['Schwarmstimmung & Varroa','Schwarmkontrollen beginnen, sobald die Entwicklung es erfordert. Befall prüfen.']],watch:'Gewichtszunahme mit Blüte, Flugwetter und Trachteintrag vergleichen.'},
 {title:'Schwarmzeit aufmerksam begleiten.',season:'Schwarmzeit',items:[['Schwarmkontrolle','In der Schwarmzeit regelmäßig, typischerweise wöchentlich, kontrollieren und Maßnahmen dokumentieren.'],['Ableger bilden','Nur ausreichend starke, gesunde Völker nutzen; Versorgung und Königinnenentwicklung der Ableger begleiten.'],['Honigräume','Platzbedarf und Reife prüfen. Weitere Honigräume nach Tracht und Besatz geben.']],watch:'Ein plötzlicher Gewichtsabfall kann ein Schwarm sein – ebenso eine Ernte oder ein Eingriff. Vor Ort prüfen.'},
 {title:'Tracht nutzen. Völker begleiten.',season:'Tracht & Ernte',items:[['Schwarmkontrolle fortführen','Schwarmneigung weiter beobachten, bis sie tatsächlich nachlässt.'],['Reifen Honig ernten','Honigreife und Wassergehalt prüfen. Den Völkern ausreichende Versorgung lassen.'],['Ableger & Varroaplan','Ablegerentwicklung prüfen und Sommerbehandlung nach Trachtende vorbereiten.']],watch:'Trachtlücken sind trotz Sommer möglich. Gewichtsverluste über mehrere Tage beachten.'},
 {title:'Gesunde Winterbienen vorbereiten.',season:'Ernte & Varroa',items:[['Honigsaison abschließen','Nach regionalem Trachtende ernten und Futterversorgung sicherstellen.'],['Varroabefall messen','Befall ermitteln und Behandlung rechtzeitig einplanen; Winterbienen sollen gesund aufwachsen.'],['Ameisensäure / Nassenheider','Nach der Honigernte nur nach zugelassener Produktanweisung, passendem Wetter und Geräteanleitung behandeln. Verdunstung kontrollieren.']],watch:'Gewichtssprünge durch abgenommene Honigräume und Fütterung bei der Auswertung berücksichtigen.'},
 {title:'Versorgen und Behandlung prüfen.',season:'Auffütterung',items:[['Auffüttern','Bedarf je Volk bestimmen und Futtergabe mit Behandlung und Volksentwicklung abstimmen. Räuberei vermeiden.'],['Behandlung kontrollieren','Wirkung über Befallskontrollen beurteilen. Beim Nassenheider Verdunstung und Wetter beobachten.'],['Volkszustand prüfen','Weiselrichtigkeit und ausreichende Stärke für den Winter bewerten.']],watch:'Das Gesamtgewicht enthält Beute, Waben, Bienen und Futter. Keine pauschale Futterreserve daraus ableiten.'},
 {title:'Die Grundlage für den Winter legen.',season:'Wintervorbereitung',items:[['Winterfutter sichern','Auffütterung bedarfsgerecht abschließen. Reserven je Volk anhand Beutentara und Kontrolle beurteilen.'],['Varroa nachkontrollieren','Befall nach der Sommerbehandlung erneut messen. Reinvasion und Handlungsbedarf beachten.'],['Dadant & Volksstärke','Futterzugang, Weiselrichtigkeit und winterfähige Volksstärke prüfen; Brutnest nicht unnötig stören.']],watch:'Nach dem Füttern dürfen die Kurven deutlich steigen. Ungeklärte Sprünge und fehlende Messungen getrennt prüfen.'},
 {title:'Den Stand winterfest machen.',season:'Wintervorbereitung',items:[['Mäuseschutz','Mäuseschutz rechtzeitig anbringen; Flugloch und Belüftung freihalten.'],['Vorräte & Stand','Futterreserve, Beutensitz und Schutz vor Wind kontrollieren. Räuberei beobachten.'],['Varroa & Bruttätigkeit','Befall weiter im Blick behalten. Winterbehandlung vorbereiten und Brutfreiheit beurteilen.']],watch:'Temperaturschwankungen, Regen und Eingriffe können Gewicht verändern. Trends über mehrere Tage betrachten.'},
 {title:'Brutfreiheit entscheidet.',season:'Winterbehandlung',items:[['Brutfreiheit prüfen','Kälte allein beweist keine Brutfreiheit. Den geeigneten Behandlungszeitpunkt am Volk beurteilen.'],['Oxalsäure-Verdampfung','Bei bestätigter Brutfreiheit nach zugelassener Produkt- und Geräteanweisung behandeln. Vorgeschriebenen Anwenderschutz beachten.'],['Winterruhe','Behandlung dokumentieren, Futter und Flugloch von außen kontrollieren.']],watch:'Nicht nach einem festen Datum behandeln. Brutfreiheit und Befall sind entscheidend.'},
 {title:'Restentmilbung und Winterruhe.',season:'Winterruhe',items:[['Winterbehandlung abschließen','Falls noch erforderlich, Brutfreiheit prüfen und Oxalsäure-Verdampfung nach Produktanweisung durchführen.'],['Erfolg & Dokumentation','Behandlung und Befallskontrolle dokumentieren; Wiederholungen nur entsprechend Produktanweisung.'],['Ruhe & Planung','Flugloch und Stand kontrollieren. Saison auswerten und Materialbedarf planen.']],watch:'Beuten möglichst geschlossen lassen. Auffällige Gewichtsverluste gezielt abklären.'}
];
